---
title: "Myeloid: Level 5"
author: "Ramon Massoni-Badosa"
date: "2021/05/13"
output: 
  BiocStyle::html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message=FALSE, warning = FALSE)
options(width = 1200)
```

NOTE: from level 4/5 onwards I will execute most steps locally, as the datasets are not as large anymore.


# Introduction

Here, we will include the annotation of the myeloid cells (level 5).


## Load packages

```{r}
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(clusterProfiler)
library(org.Hs.eg.db)
library(tidyverse)
```


## Parameters

```{r}
# Paths
path_to_myeloid_level_4 <- "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/results/R_objects/level_4/myeloid/myeloid_annotated_level_4.rds"
path_to_macrophages_level_4 <- "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/results/R_objects/level_4/myeloid/macrophages_clustered_level_4.rds"
path_to_save <- "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/results/R_objects/level_5/myeloid/myeloid_annotated_level_5.rds"


# Colors
color_palette <-  c("#1CFFCE", "#90AD1C", "#C075A6", "#85660D", "#5A5156", "#AA0DFE",   
                    "#F8A19F", "#F7E1A0", "#1C8356", "#FEAF16", "#822E1C", "#C4451C",   
                    "#1CBE4F", "#325A9B", "#F6222E", "#FE00FA", "#FBE426", "#16FF32", 
                    "black",   "#3283FE", "#B00068", "#DEA0FD", "#B10DA1", "#E4E1E3",   
                    "#90AD1C", "#FE00FA", "#85660D", "#3B00FB", "#822E1C", "coral2", 
                    "#1CFFCE", "#1CBE4F", "#3283FE", "#FBE426", "#F7E1A0", "#325A9B",   
                    "#2ED9FF", "#B5EFB5", "#5A5156", "#DEA0FD", "#FEAF16", "#683B79",   
                    "#B10DA1", "#1C7F93", "#F8A19F", "dark orange", "#FEAF16", "#FBE426",  
                    "Brown")

# Functions
source("~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/bin/utils.R")
```


## Load data

```{r}
seurat <- readRDS(path_to_myeloid_level_4)
seurat
DimPlot(seurat, cols = color_palette)
macrophages <- readRDS(path_to_macrophages_level_4)
DimPlot(macrophages, cols = color_palette)
```

# Annotation

Include annotation macrophages:

```{r}
selected_cells <- colnames(seurat)[!(colnames(seurat) %in% colnames(macrophages)[macrophages$seurat_clusters == "5"])]
seurat <- subset(seurat, cells = selected_cells)
seurat$annotation_level_4 <- seurat$annotation_level_3
c1q_hla <- colnames(macrophages)[macrophages$seurat_clusters == "0"]
selenop_fuca1_ptgds <- colnames(macrophages)[macrophages$seurat_clusters %in% c("1", "2")]
itgax_zeb2 <- colnames(macrophages)[macrophages$seurat_clusters == "3"]
il7r_mmp12 <- colnames(macrophages)[macrophages$seurat_clusters == "4"]
seurat$annotation_level_4[colnames(seurat) %in% c1q_hla] <- "C1Q HLA macrophages"
seurat$annotation_level_4[colnames(seurat) %in% selenop_fuca1_ptgds] <- "SELENOP FUCA1 PTGDS macrophages"
seurat$annotation_level_4[colnames(seurat) %in% itgax_zeb2] <- "ITGAX ZEB2 macrophages"
seurat$annotation_level_4[colnames(seurat) %in% il7r_mmp12] <- "IL7R MMP12 macrophages"
seurat$annotation_level_4[seurat$annotation_level_4 == "TBD_18_level_3"] <- "SELENOP FUCA1 PTGDS macrophages"
Idents(seurat) <- "annotation_level_4"
DimPlot(seurat, cols = color_palette, group.by = "annotation_level_4")
```



# Save

```{r}
# Macrophages
input_shiny <- seurat2shiny(seurat, slot = "data", reduction = "umap")
saveRDS(
  input_shiny$expression,
  "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/results/R_objects/level_5/myeloid/myeloid_expression_to_shiny_app_level_5.rds"
)
saveRDS(
  input_shiny$metadata,
  "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/results/R_objects/level_5/myeloid/myeloid_metadata_to_shiny_app_level_5.rds"
)
umap_level_5 <- DimPlot(seurat, cols = color_palette, pt.size = 0.75)
ggsave(
  filename = "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/3-clustering/5-level_5/myeloid/tmp/myeloid_umap_level_5.png",
  plot = umap_level_5,
  width = 14,
  height = 12,
  units = "cm"
)
saveRDS(seurat, "~/Desktop/CNAG/mnt_clust/tonsil_atlas/current/scRNA-seq/results/R_objects/level_5/myeloid/myeloid_annotated_level_5.rds")
```


# Session Info

```{r}
sessionInfo()
```
