---
title: "CD4 T: Subset (level 4)"
author: "Ramon Massoni-Badosa"
date: "2021/05/13"
output: 
  BiocStyle::html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message=FALSE, warning = FALSE)
options(width = 1200)
```


# Introduction

The purpose of this notebook is to:

1. Exclude cluster 8 and other poor-quality clusters.
2. Separate cluster 6 from the rest (naive CD8).
3. Separate clusters 12 and 13 from the rest.


## Load packages

```{r}
library(Seurat)
library(tidyverse)
```


## Parameters

```{r}
# Paths
path_to_obj <- here::here("scRNA-seq/results/R_objects/level_3/CD4_T/CD4_T_clustered_level_3_with_pre_freeze.rds")
path_to_annotation_df <- here::here("scRNA-seq/3-clustering/3-level_3/tmp/CD4_T/CD4_T_annotation_level_3_df.rds")
path_to_level_4 <- here::here("scRNA-seq/results/R_objects/level_4/CD4_T/")
dir.create(path_to_level_4, recursive = TRUE, showWarnings = FALSE)
path_to_save <- str_c(path_to_level_4, "CD4_T_subsetted_level_4.rds")
path_to_save_cd8 <- str_c(path_to_level_4, "naive_CD8_T_subsetted_level_4.rds")
path_to_save_proliferative <- str_c(path_to_level_4, "CD4_T_proliferative_subsetted_level_4.rds")
path_to_save_cd4 <- str_c(path_to_level_4, "CD4_T_subsetted_level_4.rds")


# Colors
color_palette <-  c("#1CFFCE", "#90AD1C", "#C075A6", "#85660D", "#5A5156", "#AA0DFE",   
                    "#F8A19F", "#F7E1A0", "#1C8356", "#FEAF16", "#822E1C", "#C4451C",   
                    "#1CBE4F", "#325A9B", "#F6222E", "#FE00FA", "#FBE426", "#16FF32", 
                    "black",   "#3283FE", "#B00068", "#DEA0FD", "#B10DA1", "#E4E1E3",   
                    "#90AD1C", "#FE00FA", "#85660D", "#3B00FB", "#822E1C", "coral2", 
                    "#1CFFCE", "#1CBE4F", "#3283FE", "#FBE426", "#F7E1A0", "#325A9B",   
                    "#2ED9FF", "#B5EFB5", "#5A5156", "#DEA0FD", "#FEAF16", "#683B79",   
                    "#B10DA1", "#1C7F93", "#F8A19F", "dark orange", "#FEAF16", "#FBE426",  
                    "Brown")

# Functions
source(here::here("scRNA-seq/bin/utils.R"))
```


## Load data

```{r}
# Seurat object
seurat <- readRDS(path_to_obj)
seurat


# Load annotation dataframe
annotation_df <- readRDS(path_to_annotation_df)
```


# Transfer annotation level 3

```{r}
annotation_df <- annotation_df[colnames(seurat), ]
seurat$annotation_level_3 <- annotation_df$annotation_level_3
Idents(seurat) <- "annotation_level_3"
DimPlot(seurat, cols = color_palette, pt.size = 0.2)
```


# Exclude poor-quality cells

```{r}
groups_to_exclude <- c("Doublets", "poor-quality")
selected_cells <- colnames(seurat)[!(seurat$annotation_level_3 %in% groups_to_exclude)]
seurat <- subset(seurat, cells = selected_cells)
DimPlot(seurat, cols = color_palette, pt.size = 0.2)
```


# Separate naive CD8 T, proliferative/doublets and pan-CD4 T

```{r}
cd8 <- subset(seurat, idents = "CD8")
DimPlot(cd8, cols = color_palette, pt.size = 0.2)
proliferative <- subset(seurat, idents = "Proliferative")
DimPlot(proliferative, cols = color_palette, pt.size = 0.2)
idents_cd4 <- levels(Idents(seurat))[!(levels(Idents(seurat)) %in% c("CD8", "Proliferative"))]
cd4 <- subset(seurat, idents = idents_cd4)
DimPlot(cd4, cols = color_palette, pt.size = 0.2)
```


# Save

```{r}
saveRDS(cd8, path_to_save_cd8)
saveRDS(proliferative, path_to_save_proliferative)
saveRDS(cd4, path_to_save_cd4)
```


# Session Info

```{r}
sessionInfo()
```

