---
title: 'CD4+ T cell clustering: level 3'
author: "Ramon Massoni-Badosa"
date: "12/11/2020"
output: 
  BiocStyle::html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message=FALSE, warning = FALSE)
options(width = 1200)
```


# Introduction

In this notebook, we will recluster the subclusters 1 and 3 of the level 2 of the CD4+ T cells. We will refer to such clustering as "level 3".


# Pre-processing

## Load packages

```{r packages}
library(Seurat)
library(SeuratWrappers)
library(harmony)
library(tidyverse)
```


## Define variables

```{r variables}
path_to_obj <- here::here("scRNA-seq/results/R_objects/seurat_objects_level2_clustered/CD4+_T_seurat_level2_annotated.rds")


# Paths to save (cluster 1)
path_to_save_mat_1 <- here::here("")
path_to_save_meta_1 <- here::here("")
path_to_save_markers_1 <- here::here("")
path_to_save_umap_1 <- here::here("")
path_to_save_seurat_1 <- here::here("scRNA-seq/results/R_objects/")

# Paths to save (cluster 3)

```


## Load data

```{r data}
seurat <- readRDS(path_to_obj)
```


# Subset

```{r subset}
seurat_l <- SplitObject(seurat, split.by = "seurat_clusters")
seurat_l <- seurat_l[c("1", "3")]
rm(seurat)
```


# Reprocess

```{r reprocess}
seurat_l <- purrr::map(seurat_l, function(x) {
  x <- x %>%
    FindVariableFeatures(nfeatures = 2500) %>%
    ScaleData() %>%
    RunPCA() %>%
    RunHarmony(reduction = "pca", dims = 1:30, group.by.vars = "gem_id")
  x
})
```


# Cluster

```{r cluster}
resolutions <- c(0.2, 0.7)
seurat_l <- purrr::map2(seurat_l, resolutions, function(x, res) {
  x <- FindNeighbors(x, reduction = "harmony", dims = 1:30)
  x <- FindClusters(x, resolution = res)
  x
})


# Visualize clusters
seurat_l <- purrr::map(seurat_l, function(x) {
  x <- RunUMAP(x, reduction = "harmony", dims = 1:30)
  x
})
DimPlot(seurat_l[[1]]) + DimPlot(seurat_l[[2]])
```


# Markers

```{r markers}
markers_l <- purrr::map(seurat_l, function(x) {
  df <- FindAllMarkers(
    x,
    test.use = "wilcox",
    only.pos = TRUE,
    logfc.threshold = 0.4,
    verbose = TRUE
  )
  df
})
print("Markers cluster 1")
DT::datatable(markers_l$`1`)

print("Markers cluster 3")
DT::datatable(markers_l$`3`)

markers_l_l <- purrr::map(markers_l, function(x) {
  dfs <- purrr::map(levels(x$cluster), function(k) {
    df <- x[x$cluster == k, ]
    df <- arrange(df, desc(avg_log2FC))
    df
  })
  names(dfs) <- levels(x$cluster)
  dfs
})
```


# Save

```{r save}
# Create input shiny
mat_shiny_1 <- seurat_l$`1`[["RNA"]]@data
mat_shiny_3 <- seurat_l$`3`[["RNA"]]@data
meta_shiny_1 <- seurat_l$`1`@meta.data
meta_shiny_3 <- seurat_l$`3`@meta.data
meta_shiny_1$coord_x <- seurat_l$`1`@reductions$umap@cell.embeddings[, "UMAP_1"]
meta_shiny_3$coord_x <- seurat_l$`3`@reductions$umap@cell.embeddings[, "UMAP_1"]
meta_shiny_1$coord_y <- seurat_l$`1`@reductions$umap@cell.embeddings[, "UMAP_2"]
meta_shiny_3$coord_y <- seurat_l$`3`@reductions$umap@cell.embeddings[, "UMAP_2"]
meta_shiny_1$barcode <- rownames(meta_shiny_1)
meta_shiny_3$barcode <- rownames(meta_shiny_3)


# Save shiny

```


# Session Information

```{r sessionInfo}
sessionInfo()
```

